# Generated by Django 6.0.3 on 2026-06-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_topic_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
